# tasks file
---
- name: configure | stat directories
  stat:
    path: "{{ item }}/"
  register: _stat_directories
  with_items:
    - "{{ influxdb_meta_dir }}"
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_data_wal_dir }}"
  tags:
    - influxdb-configure-directories
    - influxdb-configure-directories-stat

- name: configure | create directories
  file:
    path: "{{ item.item }}"
    state: directory
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_group }}"
    mode: 0750
  with_items: "{{ _stat_directories.results }}"
  when: not item.stat.exists
  tags:
    - influxdb-configure-directories
    - influxdb-configure-directories-create

- name: configure | update configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  notify: restart influxdb
  with_items:
    - src: etc/influxdb/influxdb.conf.j2
      dest: /etc/influxdb/influxdb.conf
    - src: etc/default/influxdb.j2
      dest: /etc/default/influxdb
  tags:
    - influxdb-configure-configuration
    - influxdb-configure-configuration-files
