# tasks file for influxdb
---
- name: configure | stat directories
  stat:
    path: "{{ item }}/"
  register: _stat_directories
  with_items:
    - "{{ influxdb_influxdb_home }}"
    - "{{ influxdb_log_dir }}"
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_conf_dir }}"
    - "{{ influxdb_plugins_dir }}"
    - "{{ influxdb_pid_file_dir }}"
  tags:
    - influxdb-configure-directories
    - influxdb-configure-directories-stat

- name: configure | create directories
  file:
    path: "{{ item.item }}"
    state: directory
    owner: "{{ influxdb_influxdb_user }}"
    group: "{{ influxdb_influxdb_group }}"
    mode: 0755
  with_items: "{{ _stat_directories.results }}"
  when: item.stat.exists == false
  tags:
    - influxdb-configure-directories
    - influxdb-configure-directories-create

- name: configure | update configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  notify: restart influxdb
  with_items:
    - src: etc/influxdb/influxdb.ini.j2
      dest: "{{ influxdb_conf_file }}"
      owner: root
      group: "{{ influxdb_influxdb_group }}"
      mode: '0640'
    - src: etc/default/influxdb-server.j2
      dest: /etc/default/influxdb-server
      owner: root
      group: root
      mode: '0644'
  tags:
    - influxdb-configure-configuration
    - influxdb-configure-configuration-files
