# tasks file for influxdb
---
- name: databases | query show
  command: >
    curl -sSf -X GET
    http://localhost:8086/query?q={{ 'SHOW DATABASES' | urlencode }}
  args:
    warn: false
  register: _show_databases
  changed_when: false
  tags:
    - influxdb-databases-query-show

- name: databases | format show
  set_fact:
    _databases_present: "{{ _show_databases.stdout | from_json }}"
  tags:
    - influxdb-databases-format-show

- name: databases | set show
  set_fact:
    _databases_present: "{{ _databases_present['results'][0]['series'][0].get('values', {}) | map(attribute=0) | list }}"
  tags:
    - influxdb-databases-set-show

- name: databases | create
  command: >
    curl -sSf -X POST
    http://localhost:8086/query?q={{ ('CREATE DATABASE ' + item.name + (' WITH DURATION ' + item.duration if item.duration is defined else '') ) | urlencode }}
  args:
    warn: false
  with_items: "{{ influxdb_databases_present }}"
  when: item.name not in _databases_present
  tags:
    - influxdb-databases-create

- name: databases | drop
  command: >
    curl -sSf -X POST
    http://localhost:8086/query?q={{ ('DROP DATABASE ' + item) | urlencode }}
  args:
    warn: false
  with_items: "{{ influxdb_databases_absent }}"
  when: item in _databases_present
  tags:
    - influxdb-databases-drop
