# tasks file for influxdb
---
- name: databases | query show
  uri:
    url: "http://localhost:8086/query?q={{ 'SHOW DATABASES' | urlencode }}"
    method: POST
    return_content: true
    user: "{{ influxdb_admin_username | default(omit) }}"
    password: "{{ influxdb_admin_password | default(omit) }}"
    status_code: 200
  register: _show_databases
  tags:
    - influxdb-databases-query-show

# TODO: Use json query?
- name: databases | set show
  set_fact:
    _databases_present: "{{ _show_databases['json']['results'][0]['series'][0]['values'] | default({values: [[]]}) | map(attribute=0) | list }}"
  tags:
    - influxdb-databases-set-show

- name: databases | create
  uri:
    url: "http://localhost:8086/query?q={{ ('CREATE DATABASE ' + item.name + (' WITH DURATION ' + item.duration if item.duration is defined else '') ) | urlencode }}"
    method: 'POST'
    user: "{{ influxdb_admin_username | default(omit) }}"
    password: "{{ influxdb_admin_password | default(omit) }}"
    status_code: 200
  changed_when: true
  with_items: "{{ influxdb_databases_present }}"
  when: item.name not in _databases_present
  tags:
    - influxdb-databases-create

- name: databases | drop
  uri:
    url: "http://localhost:8086/query?q={{ ('DROP DATABASE ' + item) | urlencode }}"
    method: 'POST'
    user: "{{ influxdb_admin_username | default(omit) }}"
    password: "{{ influxdb_admin_password | default(omit) }}"
    status_code: 200
  changed_when: true
  with_items: "{{ influxdb_databases_absent }}"
  when: item in _databases_present
  tags:
    - influxdb-databases-drop
