# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ influxdb_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - influxdb-install-dependencies

- name: install | dependencies | check service
  ansible.builtin.service:
    name: influxdb
    state: started
  tags:
    - influxdb-install-dependencies
    - influxdb-install-dependencies-check

- name: install | additional
  ansible.builtin.apt:
    name: "{{ influxdb_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - influxdb-install-additional
