# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - influxdb
    - influxdb-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - influxdb
    - influxdb-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - influxdb
    - influxdb-configure

- name: databases
  ansible.builtin.import_tasks: databases.yml
  tags:
    - configuration
    - influxdb
    - influxdb-databases

- name: collectd
  ansible.builtin.import_tasks: collectd.yml
  tags:
    - configuration
    - influxdb
    - influxdb-collectd

- name: start and enable service
  ansible.builtin.service:
    name: influxdb
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - influxdb-start-enable-service
