# tasks file
---
- include: repository.yml
  tags:
    - configuration
    - influxdb
    - influxdb-repository

- include: install.yml
  tags:
    - configuration
    - influxdb
    - influxdb-install

- include: configure.yml
  tags:
    - configuration
    - influxdb
    - influxdb-configure

- include: databases.yml
  tags:
    - configuration
    - influxdb
    - influxdb-databases

- include: collectd.yml
  tags:
    - configuration
    - influxdb
    - influxdb-collectd

- name: start and enable service
  service:
    name: influxdb
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - influxdb-start-enable-service
