# tasks file
---
- name: repository | dependencies
  ansible.builtin.apt:
    name: "{{ influxdb_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - influxdb-repository-dependencies

- name: repository | add public key
  ansible.builtin.apt_key:
    id: "{{ item.id }}"
    keyserver: "{{ item.keyserver }}"
    state: present
  with_items: "{{ influxdb_apt_keys }}"
  tags:
    - influxdb-repository-public-key

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ influxdb_repositories }}"
  tags:
    - influxdb-repository-add
